#!/usr/bin/env bash
# LinuxOps Toolkit -recomendaciones

# CPU
CPU_REC="Revisar procesos con alto consumo utilizando top/htop."

# MEMORIA
MEM_REC="Verificar procesos usando la memoria RAM o considerar liberar caché de Swap."

# HDD / SSD
DISK_REC="Limpiar archivos de log antiguos y paquetes no utilizados con apt/yum/dnf clean."

# NETWORK
NETWORK_WARNING="Verificar configuración DNS, tablas de enrutamiento ('ip route') o reglas del Firewall local."
NETWORK_CRITICAL="Revisar conexión física (cable/Wi-Fi), verificar encendido de la interfaz o reiniciar NetworkManager."
