#!/usr/bin/env bash
# LinuxOps Toolkit -recomendaciones

# CPU
CPU_REC="Revisar procesos con alto consumo utilizando top/htop."

# MEMORIA
MEM_REC="Verificar procesos usando la memoria RAM o considerar liberar caché de Swap."

# HDD / SSD
DISK_REC="Limpiar archivos de log antiguos y paquetes no utilizados con apt/yum/dnf clean."

# NETWORK
NETWORK_WARNING="Verificar configuración DNS, tablas de enrutamiento ('ip route') o reglas del Firewall local."
NETWORK_CRITICAL="Revisar conexión física (cable/Wi-Fi), verificar encendido de la interfaz o reiniciar NetworkManager."

# PROCESS
# Procesos Zombie
PROCESS_WARNING_ZOMBIE="Monitorear si el número crece. Si persiste, identificar el PPID para reiniciarlo." 
PROCESS_CRITICAL_ZOMBIE="¡CRÍTICO! Identificar de inmediato el proceso padre con fugas y aplicar un reinicio forzado del servicio."

# Consumo de CPU por Proceso
PROCESS_WARNING_CPU="Verificar los hilos de la aplicación. Podría ser una tarea pesada programada (cron)." 
PROCESS_CRITICAL_CPU="Considerar aplicar 'renice' para bajar su prioridad o ejecutar 'kill -15 <PID>' para cerrarlo de forma segura."

# Consumo de RAM por Proceso
PROCESS_WARNING_MEM="Monitorear fugas de memoria (memory leaks). Revisar la recolección de basura (Garbage Collector) de la app." 
PROCESS_CRITICAL_MEM="Peligro de OOM Killer. Liberar caché del sistema o programar un reinicio controlado del servicio afectado."
