#!/usr/bin/env bash
# LinuxOps Toolkit -recomendaciones

# -----CPU-----
CPU_WARN_REC="Revisar los procesos con mayor consumo de CPU y validar si la carga corresponde a tareas programadas o picos temporales."
CPU_CRIT_REC="Identificar procesos que saturan la CPU, ajustar su prioridad o reiniciar el servicio afectado. Si la carga es persistente, evaluar el escalamiento de recursos."

# -----MEMORIA-----
# Uso de memoria RAM
MEM_WARN_REC="Identificar procesos con alto consumo de memoria, revisar posibles memory leaks y validar el uso de swap."
MEM_CRIT_REC="Liberar memoria inmediatamente deteniendo procesos no esenciales. Verificar el uso de swap e investigar fugas de memoria. Si el consumo es constante, considerar ampliar la RAM."

# -----HDD / SSD-----
DISK_WARN_REC="Analizar el crecimiento del sistema de archivos. Revisar directorios con mayor consumo, aplicar rotación de logs y eliminar archivos innecesarios."
DISK_CRIT_REC="Uso crítico del sistema de archivos. Liberar espacio inmediatamente o ampliar el volumen (LVM/partición) para evitar la interrupción de servicios."

# -----NETWORK-----
NETWORK_WARNING="Verificar configuración DNS, tablas de enrutamiento ('ip route') o reglas del Firewall local."
NETWORK_CRITICAL="Revisar conexión física (cable/Wi-Fi), verificar encendido de la interfaz o reiniciar NetworkManager."

# -----PROCESS----
# Procesos Zombie
PROCESS_WARNING_ZOMBIE="Monitorear si el número crece. Si persiste, identificar el PPID para reiniciarlo." 
PROCESS_CRITICAL_ZOMBIE="¡CRÍTICO! Identificar de inmediato el proceso padre con fugas y aplicar un reinicio forzado del servicio."
# Consumo de CPU por Proceso
PROCESS_WARNING_CPU="Analizar el proceso con mayor consumo de CPU. Verificar si corresponde a una carga esperada o a un comportamiento anómalo." 
PROCESS_CRITICAL_CPU="Investigar la causa del consumo elevado. Optimizar la aplicación o reiniciar el servicio si afecta la estabilidad del sistema."
# Consumo de RAM por Proceso
PROCESS_WARNING_MEM="Verificar posibles fugas de memoria o un consumo inusual de la aplicación. Confirmar que el uso sea esperado."
PROCESS_CRITICAL_MEM="Existe riesgo de activación del OOM Killer. Identificar el proceso responsable y considerar reiniciar el servicio o aumentar los recursos disponibles."

# -----USER------
# Auditoría de Cuentas UID 0 (Seguridad Alta)
USERS_CRITICAL_UID0="¡ALERTA DE SEGURIDAD! Se detectó una mas cuentas no-root con UID 0.
Auditar '/etc/passwd' inmediatamente y revocar el acceso para prevenir un backdoor."
# Concurrencia de Sesiones Activas
USERS_WARNING_SESSIONS="Alto número de sesiones TTY/PTS abiertas.
Ejecutar 'w' para inspeccionar usuarios conectados y cerrar sesiones inactivas con 'pkill -kill -u <usuario>' o 'logout'."
# Intentos de Acceso Fallidos (Brute Force / SSH)
USERS_WARNING_FAILED_LOGINS="Múltiples intentos fallidos de inicio de sesión detectados.
Revisar logs con 'journalctl -u sshd' o '/var/log/secure' y considerar bloquear IP agresivas con Fail2ban o reglas de Firewall."
USERS_CRITICAL_FAILED_LOGINS="¡POSIBLE ATAQUE DE FUERZA BRUTA! Alta tasa de autenticaciones fallidas.
Verificar reglas de 'firewalld'/'iptables', restringir accesos SSH por llave privada (RSA/Ed25519) y deshabilitar login de root."

# -----SYSINFO-----
SYS_WARNING_UPTIME_180DAYS="El host lleva más de 180 días de actividad continua. Revisar con 'uptime' y planificar un reinicio controlado si es necesario."