#!/usr/bin/env bash
# LinuxOps Toolkit - Umbrales

# CPU
CPU_WARN_THRESHOLD=70
CPU_CRIT_THRESHOLD=85

# MEMORIA
MEM_WARN_THRESHOLD=75
MEM_CRIT_THRESHOLD=90

#DISCO
DISK_WARN_THRESHOLD=80
DISK_CRIT_THRESHOLD=90